//! Metal Shading Language (MSL) Code Generation
//!
//! Native Apple Metal backend for Demetrios GPU computing.
//! Supports M1/M2/M3 Apple Silicon and Intel Macs.
//!
//! # Architecture
//!
//! ```text
//! GPU IR ──> MSL Source ──> Metal Compiler ──> GPU Binary
//! ```
//!
//! # Metal vs CUDA Mapping
//!
//! | CUDA Concept | Metal Equivalent |
//! |--------------|------------------|
//! | Thread | Thread |
//! | Warp (32) | Simdgroup (32) |
//! | Block | Threadgroup |
//! | Grid | Grid |
//! | `__shared__` | `threadgroup` |
//! | `__device__` | `device` |
//! | `__constant__` | `constant` |
//! | `atomicAdd` | `atomic_fetch_add_explicit` |
//! | `__syncthreads()` | `threadgroup_barrier(mem_flags::mem_threadgroup)` |
//! | `__shfl_xor_sync` | `simd_shuffle_xor` |
//!
//! # Epistemic Shadow Variables in MSL
//!
//! ```metal
//! struct EpistemicFloat {
//!     float value;
//!     float epsilon;      // Uncertainty bound
//!     bool valid;         // Validity flag
//!     uint64_t provenance; // Data lineage
//! };
//! ```

use std::collections::HashMap;
use std::fmt::Write;

use super::ir::*;

/// Metal codegen configuration
#[derive(Debug, Clone)]
pub struct MetalCodegenConfig {
    /// Target GPU family
    pub gpu_family: MetalGpuFamily,
    /// Enable fast math optimizations
    pub fast_math: bool,
    /// Generate debug info
    pub debug_info: bool,
    /// Enable epistemic tracking
    pub epistemic_enabled: bool,
    /// Maximum threads per threadgroup
    pub max_threads_per_threadgroup: u32,
}

impl Default for MetalCodegenConfig {
    fn default() -> Self {
        Self {
            gpu_family: MetalGpuFamily::Apple8,
            fast_math: true,
            debug_info: false,
            epistemic_enabled: true,
            max_threads_per_threadgroup: 256,
        }
    }
}

/// Metal Shading Language code generator
pub struct MetalCodegen {
    config: MetalCodegenConfig,
    output: String,
    indent: usize,
    value_counter: u32,
    /// Map from GPU IR values to MSL variable names
    value_names: HashMap<ValueId, String>,
}

impl MetalCodegen {
    pub fn new(config: MetalCodegenConfig) -> Self {
        Self {
            config,
            output: String::with_capacity(16384),
            indent: 0,
            value_counter: 0,
            value_names: HashMap::new(),
        }
    }

    /// Generate MSL code from GPU module
    pub fn generate(&mut self, module: &GpuModule) -> String {
        self.output.clear();
        self.emit_header();
        self.emit_epistemic_types();
        self.emit_epistemic_functions();
        self.emit_simdgroup_helpers();

        // Generate constants
        for constant in &module.constants {
            self.emit_constant(constant);
        }

        // Generate device functions
        for (_, func) in &module.device_functions {
            self.emit_device_function(func);
        }

        // Generate kernels
        for (_, kernel) in &module.kernels {
            self.emit_kernel(kernel);
        }

        std::mem::take(&mut self.output)
    }

    fn emit(&mut self, s: &str) {
        let indent = "    ".repeat(self.indent);
        writeln!(self.output, "{}{}", indent, s).unwrap();
    }

    fn emit_raw(&mut self, s: &str) {
        writeln!(self.output, "{}", s).unwrap();
    }

    fn fresh_var(&mut self, prefix: &str) -> String {
        let name = format!("{}_{}", prefix, self.value_counter);
        self.value_counter += 1;
        name
    }

    fn emit_header(&mut self) {
        let msl_version = self.config.gpu_family.msl_version();
        self.emit_raw(&format!(
            "// Generated by Demetrios Compiler - Metal Backend"
        ));
        self.emit_raw(&format!("// Target: {:?}", self.config.gpu_family));
        self.emit_raw(&format!("// MSL Version: {}", msl_version));
        self.emit_raw("");
        self.emit_raw("#include <metal_stdlib>");
        self.emit_raw("#include <simdgroup_matrix>");
        self.emit_raw("using namespace metal;");
        self.emit_raw("");

        if self.config.fast_math {
            self.emit_raw("// Fast math enabled");
            self.emit_raw("#pragma clang fp contract(fast)");
            self.emit_raw("");
        }
    }

    fn emit_epistemic_types(&mut self) {
        if !self.config.epistemic_enabled {
            return;
        }

        self.emit_raw("// ============================================");
        self.emit_raw("// Epistemic Types - Shadow Variables for Uncertainty");
        self.emit_raw("// ============================================");
        self.emit_raw("");

        // EpistemicFloat - single precision with uncertainty tracking
        self.emit_raw("struct EpistemicFloat {");
        self.emit_raw("    float value;           // Actual value");
        self.emit_raw("    float epsilon;         // Uncertainty bound (σ)");
        self.emit_raw("    bool valid;            // Validity flag");
        self.emit_raw("    uint64_t provenance;   // Data lineage bitmask");
        self.emit_raw("");
        self.emit_raw("    // Constructors");
        self.emit_raw("    EpistemicFloat() : value(0), epsilon(0), valid(true), provenance(0) {}");
        self.emit_raw(
            "    EpistemicFloat(float v) : value(v), epsilon(0), valid(true), provenance(0) {}",
        );
        self.emit_raw("    EpistemicFloat(float v, float e) : value(v), epsilon(e), valid(true), provenance(0) {}");
        self.emit_raw("    EpistemicFloat(float v, float e, bool val, uint64_t prov)");
        self.emit_raw("        : value(v), epsilon(e), valid(val), provenance(prov) {}");
        self.emit_raw("");
        self.emit_raw("    // Confidence level (1 - epsilon for small epsilon)");
        self.emit_raw("    float confidence() const { return 1.0f - epsilon; }");
        self.emit_raw("};");
        self.emit_raw("");

        // EpistemicFloat2/3/4 for vector operations
        self.emit_raw("struct EpistemicFloat2 {");
        self.emit_raw("    float2 value;");
        self.emit_raw("    float2 epsilon;");
        self.emit_raw("    bool2 valid;");
        self.emit_raw("    uint64_t provenance;");
        self.emit_raw("};");
        self.emit_raw("");

        self.emit_raw("struct EpistemicFloat4 {");
        self.emit_raw("    float4 value;");
        self.emit_raw("    float4 epsilon;");
        self.emit_raw("    bool4 valid;");
        self.emit_raw("    uint64_t provenance;");
        self.emit_raw("};");
        self.emit_raw("");
    }

    fn emit_epistemic_functions(&mut self) {
        if !self.config.epistemic_enabled {
            return;
        }

        self.emit_raw("// ============================================");
        self.emit_raw("// Epistemic Operations - Uncertainty Propagation");
        self.emit_raw("// ============================================");
        self.emit_raw("");

        // Epistemic addition with quadrature propagation
        self.emit_raw("// Epistemic add: ε_c = √(ε_a² + ε_b²)");
        self.emit_raw("inline EpistemicFloat epistemic_add(EpistemicFloat a, EpistemicFloat b) {");
        self.emit_raw("    EpistemicFloat result;");
        self.emit_raw("    result.value = a.value + b.value;");
        self.emit_raw("    result.epsilon = sqrt(a.epsilon * a.epsilon + b.epsilon * b.epsilon);");
        self.emit_raw("    result.valid = a.valid && b.valid;");
        self.emit_raw("    result.provenance = a.provenance ^ b.provenance;");
        self.emit_raw("    return result;");
        self.emit_raw("}");
        self.emit_raw("");

        // Epistemic subtraction
        self.emit_raw("// Epistemic sub: same propagation as add");
        self.emit_raw("inline EpistemicFloat epistemic_sub(EpistemicFloat a, EpistemicFloat b) {");
        self.emit_raw("    EpistemicFloat result;");
        self.emit_raw("    result.value = a.value - b.value;");
        self.emit_raw("    result.epsilon = sqrt(a.epsilon * a.epsilon + b.epsilon * b.epsilon);");
        self.emit_raw("    result.valid = a.valid && b.valid;");
        self.emit_raw("    result.provenance = a.provenance ^ b.provenance;");
        self.emit_raw("    return result;");
        self.emit_raw("}");
        self.emit_raw("");

        // Epistemic multiplication
        self.emit_raw("// Epistemic mul: ε_c ≈ |a|·ε_b + |b|·ε_a");
        self.emit_raw("inline EpistemicFloat epistemic_mul(EpistemicFloat a, EpistemicFloat b) {");
        self.emit_raw("    EpistemicFloat result;");
        self.emit_raw("    result.value = a.value * b.value;");
        self.emit_raw("    result.epsilon = abs(a.value) * b.epsilon + abs(b.value) * a.epsilon;");
        self.emit_raw("    result.valid = a.valid && b.valid;");
        self.emit_raw("    result.provenance = a.provenance ^ b.provenance;");
        self.emit_raw("    return result;");
        self.emit_raw("}");
        self.emit_raw("");

        // Epistemic division
        self.emit_raw("// Epistemic div: ε_c ≈ (|a|·ε_b + |b|·ε_a) / b²");
        self.emit_raw("inline EpistemicFloat epistemic_div(EpistemicFloat a, EpistemicFloat b) {");
        self.emit_raw("    EpistemicFloat result;");
        self.emit_raw("    float b_sq = b.value * b.value;");
        self.emit_raw("    result.value = a.value / b.value;");
        self.emit_raw(
            "    result.epsilon = (abs(a.value) * b.epsilon + abs(b.value) * a.epsilon) / b_sq;",
        );
        self.emit_raw("    result.valid = a.valid && b.valid && (abs(b.value) > 1e-10f);");
        self.emit_raw("    result.provenance = a.provenance ^ b.provenance;");
        self.emit_raw("    return result;");
        self.emit_raw("}");
        self.emit_raw("");

        // Epistemic FMA
        self.emit_raw("// Epistemic fma: a * b + c");
        self.emit_raw("inline EpistemicFloat epistemic_fma(EpistemicFloat a, EpistemicFloat b, EpistemicFloat c) {");
        self.emit_raw("    EpistemicFloat ab = epistemic_mul(a, b);");
        self.emit_raw("    return epistemic_add(ab, c);");
        self.emit_raw("}");
        self.emit_raw("");

        // Epistemic sqrt
        self.emit_raw("// Epistemic sqrt: ε_c = ε_a / (2·√a)");
        self.emit_raw("inline EpistemicFloat epistemic_sqrt(EpistemicFloat a) {");
        self.emit_raw("    EpistemicFloat result;");
        self.emit_raw("    result.value = sqrt(a.value);");
        self.emit_raw("    result.epsilon = a.epsilon / (2.0f * result.value);");
        self.emit_raw("    result.valid = a.valid && (a.value >= 0.0f);");
        self.emit_raw("    result.provenance = a.provenance;");
        self.emit_raw("    return result;");
        self.emit_raw("}");
        self.emit_raw("");

        // Epistemic exp
        self.emit_raw("// Epistemic exp: ε_c = exp(a) · ε_a");
        self.emit_raw("inline EpistemicFloat epistemic_exp(EpistemicFloat a) {");
        self.emit_raw("    EpistemicFloat result;");
        self.emit_raw("    result.value = exp(a.value);");
        self.emit_raw("    result.epsilon = result.value * a.epsilon;");
        self.emit_raw("    result.valid = a.valid;");
        self.emit_raw("    result.provenance = a.provenance;");
        self.emit_raw("    return result;");
        self.emit_raw("}");
        self.emit_raw("");

        // Epistemic log
        self.emit_raw("// Epistemic log: ε_c = ε_a / a");
        self.emit_raw("inline EpistemicFloat epistemic_log(EpistemicFloat a) {");
        self.emit_raw("    EpistemicFloat result;");
        self.emit_raw("    result.value = log(a.value);");
        self.emit_raw("    result.epsilon = a.epsilon / a.value;");
        self.emit_raw("    result.valid = a.valid && (a.value > 0.0f);");
        self.emit_raw("    result.provenance = a.provenance;");
        self.emit_raw("    return result;");
        self.emit_raw("}");
        self.emit_raw("");

        // Confidence gate
        self.emit_raw("// Check if confidence exceeds threshold");
        self.emit_raw("inline bool confidence_gate(EpistemicFloat a, float threshold) {");
        self.emit_raw("    return a.valid && (a.epsilon < (1.0f - threshold));");
        self.emit_raw("}");
        self.emit_raw("");
    }

    fn emit_simdgroup_helpers(&mut self) {
        self.emit_raw("// ============================================");
        self.emit_raw("// Simdgroup Operations (CUDA warp equivalent)");
        self.emit_raw("// ============================================");
        self.emit_raw("");

        // Simdgroup reduce for epistemic values
        if self.config.epistemic_enabled {
            self.emit_raw("// Simdgroup-wide epsilon reduction (max)");
            self.emit_raw("inline float simdgroup_epsilon_max(float epsilon) {");
            self.emit_raw("    return simd_max(epsilon);");
            self.emit_raw("}");
            self.emit_raw("");

            self.emit_raw("// Simdgroup-wide epsilon reduction (min)");
            self.emit_raw("inline float simdgroup_epsilon_min(float epsilon) {");
            self.emit_raw("    return simd_min(epsilon);");
            self.emit_raw("}");
            self.emit_raw("");

            self.emit_raw("// Simdgroup-wide validity vote (count valid)");
            self.emit_raw("inline uint simdgroup_validity_count(bool valid) {");
            self.emit_raw("    return popcount(simd_ballot(valid));");
            self.emit_raw("}");
            self.emit_raw("");

            self.emit_raw("// Simdgroup-wide epistemic reduce (sum values, max epsilon)");
            self.emit_raw("inline EpistemicFloat simdgroup_epistemic_sum(EpistemicFloat a) {");
            self.emit_raw("    EpistemicFloat result;");
            self.emit_raw("    result.value = simd_sum(a.value);");
            self.emit_raw("    result.epsilon = simd_max(a.epsilon);  // Conservative bound");
            self.emit_raw("    result.valid = simd_all(a.valid);");
            self.emit_raw("    result.provenance = 0;  // Aggregated");
            self.emit_raw("    return result;");
            self.emit_raw("}");
            self.emit_raw("");
        }

        // Standard simdgroup helpers
        self.emit_raw("// Simdgroup shuffle XOR (for reductions)");
        self.emit_raw("template<typename T>");
        self.emit_raw("inline T simdgroup_shuffle_xor(T value, ushort mask) {");
        self.emit_raw("    return simd_shuffle_xor(value, mask);");
        self.emit_raw("}");
        self.emit_raw("");

        self.emit_raw("// Simdgroup broadcast from lane 0");
        self.emit_raw("template<typename T>");
        self.emit_raw("inline T simdgroup_broadcast_first(T value) {");
        self.emit_raw("    return simd_broadcast_first(value);");
        self.emit_raw("}");
        self.emit_raw("");
    }

    fn emit_constant(&mut self, constant: &GpuConstant) {
        let ty = self.type_to_msl(&constant.ty);
        let value = self.const_value_to_msl(&constant.value);
        self.emit_raw(&format!("constant {} {} = {};", ty, constant.name, value));
    }

    fn emit_device_function(&mut self, func: &GpuFunction) {
        let return_ty = self.type_to_msl(&func.return_type);
        let params = self.params_to_msl(&func.params);

        let inline = if func.inline { "inline " } else { "" };
        self.emit_raw(&format!(
            "{}{}  {}({}) {{",
            inline, return_ty, func.name, params
        ));

        self.indent += 1;
        for block in &func.blocks {
            self.emit_block(block);
        }
        self.indent -= 1;

        self.emit_raw("}");
        self.emit_raw("");
    }

    fn emit_kernel(&mut self, kernel: &GpuKernel) {
        self.emit_raw(&format!("// Kernel: {}", kernel.name));

        // Emit threadgroup memory declarations
        for shared in &kernel.shared_memory {
            let ty = self.type_to_msl(&shared.elem_type);
            self.emit_raw(&format!(
                "// Shared memory: {} {}[{}]",
                ty, shared.name, shared.size
            ));
        }

        // Build parameter list
        let mut params = Vec::new();

        // Regular parameters
        for (i, param) in kernel.params.iter().enumerate() {
            let ty = self.type_to_msl(&param.ty);
            let space = self.memory_space_to_msl(param.space);
            params.push(format!("{} {} {} [[buffer({})]]", space, ty, param.name, i));
        }

        // Add threadgroup memory parameters
        for (i, shared) in kernel.shared_memory.iter().enumerate() {
            let ty = self.type_to_msl(&shared.elem_type);
            params.push(format!(
                "threadgroup {}* {} [[threadgroup({})]]",
                ty, shared.name, i
            ));
        }

        // Add built-in parameters
        params.push("uint3 thread_position_in_grid [[thread_position_in_grid]]".to_string());
        params.push(
            "uint3 thread_position_in_threadgroup [[thread_position_in_threadgroup]]".to_string(),
        );
        params.push(
            "uint3 threadgroup_position_in_grid [[threadgroup_position_in_grid]]".to_string(),
        );
        params.push("uint3 threads_per_threadgroup [[threads_per_threadgroup]]".to_string());
        params.push("uint simd_lane_id [[thread_index_in_simdgroup]]".to_string());
        params.push("uint simd_group_id [[simdgroup_index_in_threadgroup]]".to_string());

        let params_str = params.join(",\n    ");

        self.emit_raw(&format!("kernel void {}(", kernel.name));
        self.emit_raw(&format!("    {}", params_str));
        self.emit_raw(") {");

        // Emit local variable declarations
        self.indent += 1;

        // Thread indices (CUDA compatibility)
        self.emit("// Thread indices (CUDA-style naming)");
        self.emit("uint threadIdx_x = thread_position_in_threadgroup.x;");
        self.emit("uint threadIdx_y = thread_position_in_threadgroup.y;");
        self.emit("uint threadIdx_z = thread_position_in_threadgroup.z;");
        self.emit("uint blockIdx_x = threadgroup_position_in_grid.x;");
        self.emit("uint blockIdx_y = threadgroup_position_in_grid.y;");
        self.emit("uint blockIdx_z = threadgroup_position_in_grid.z;");
        self.emit("uint blockDim_x = threads_per_threadgroup.x;");
        self.emit("uint blockDim_y = threads_per_threadgroup.y;");
        self.emit("uint blockDim_z = threads_per_threadgroup.z;");
        self.emit("uint globalIdx = thread_position_in_grid.x;");
        self.emit("");

        // Emit blocks
        for block in &kernel.blocks {
            self.emit_block(block);
        }

        self.indent -= 1;
        self.emit_raw("}");
        self.emit_raw("");
    }

    fn emit_block(&mut self, block: &GpuBlock) {
        if !block.label.is_empty() {
            self.emit(&format!("{}: // Block {}", block.label, block.id));
        }

        for (value_id, op) in &block.instructions {
            self.emit_instruction(*value_id, op);
        }

        self.emit_terminator(&block.terminator);
    }

    fn emit_instruction(&mut self, result: ValueId, op: &GpuOp) {
        let result_name = self.get_or_create_var_name(result);

        match op {
            // Constants
            GpuOp::ConstInt(val, ty) => {
                let ty_str = self.type_to_msl(ty);
                self.emit(&format!("{} {} = {};", ty_str, result_name, val));
            }
            GpuOp::ConstFloat(val, ty) => {
                let ty_str = self.type_to_msl(ty);
                self.emit(&format!("{} {} = {}f;", ty_str, result_name, val));
            }
            GpuOp::ConstBool(val) => {
                self.emit(&format!("bool {} = {};", result_name, val));
            }

            // Arithmetic
            GpuOp::Add(a, b) => {
                let a_name = self.get_var_name(*a);
                let b_name = self.get_var_name(*b);
                self.emit(&format!("auto {} = {} + {};", result_name, a_name, b_name));
            }
            GpuOp::Sub(a, b) => {
                let a_name = self.get_var_name(*a);
                let b_name = self.get_var_name(*b);
                self.emit(&format!("auto {} = {} - {};", result_name, a_name, b_name));
            }
            GpuOp::Mul(a, b) => {
                let a_name = self.get_var_name(*a);
                let b_name = self.get_var_name(*b);
                self.emit(&format!("auto {} = {} * {};", result_name, a_name, b_name));
            }
            GpuOp::Div(a, b) => {
                let a_name = self.get_var_name(*a);
                let b_name = self.get_var_name(*b);
                self.emit(&format!("auto {} = {} / {};", result_name, a_name, b_name));
            }
            GpuOp::Rem(a, b) => {
                let a_name = self.get_var_name(*a);
                let b_name = self.get_var_name(*b);
                self.emit(&format!("auto {} = {} % {};", result_name, a_name, b_name));
            }
            GpuOp::Neg(a) => {
                let a_name = self.get_var_name(*a);
                self.emit(&format!("auto {} = -{};", result_name, a_name));
            }

            // Float arithmetic
            GpuOp::FAdd(a, b) => {
                let a_name = self.get_var_name(*a);
                let b_name = self.get_var_name(*b);
                self.emit(&format!("float {} = {} + {};", result_name, a_name, b_name));
            }
            GpuOp::FSub(a, b) => {
                let a_name = self.get_var_name(*a);
                let b_name = self.get_var_name(*b);
                self.emit(&format!("float {} = {} - {};", result_name, a_name, b_name));
            }
            GpuOp::FMul(a, b) => {
                let a_name = self.get_var_name(*a);
                let b_name = self.get_var_name(*b);
                self.emit(&format!("float {} = {} * {};", result_name, a_name, b_name));
            }
            GpuOp::FDiv(a, b) => {
                let a_name = self.get_var_name(*a);
                let b_name = self.get_var_name(*b);
                self.emit(&format!("float {} = {} / {};", result_name, a_name, b_name));
            }
            GpuOp::FNeg(a) => {
                let a_name = self.get_var_name(*a);
                self.emit(&format!("float {} = -{};", result_name, a_name));
            }

            // Fast math
            GpuOp::FMulAdd(a, b, c) => {
                let a_name = self.get_var_name(*a);
                let b_name = self.get_var_name(*b);
                let c_name = self.get_var_name(*c);
                self.emit(&format!(
                    "float {} = fma({}, {}, {});",
                    result_name, a_name, b_name, c_name
                ));
            }
            GpuOp::FastSin(a) => {
                let a_name = self.get_var_name(*a);
                self.emit(&format!("float {} = sin({});", result_name, a_name));
            }
            GpuOp::FastCos(a) => {
                let a_name = self.get_var_name(*a);
                self.emit(&format!("float {} = cos({});", result_name, a_name));
            }
            GpuOp::FastExp(a) => {
                let a_name = self.get_var_name(*a);
                self.emit(&format!("float {} = exp({});", result_name, a_name));
            }
            GpuOp::FastLog(a) => {
                let a_name = self.get_var_name(*a);
                self.emit(&format!("float {} = log({});", result_name, a_name));
            }
            GpuOp::FastSqrt(a) => {
                let a_name = self.get_var_name(*a);
                self.emit(&format!("float {} = sqrt({});", result_name, a_name));
            }
            GpuOp::FastRsqrt(a) => {
                let a_name = self.get_var_name(*a);
                self.emit(&format!("float {} = rsqrt({});", result_name, a_name));
            }

            // Comparisons
            GpuOp::Eq(a, b) => {
                let a_name = self.get_var_name(*a);
                let b_name = self.get_var_name(*b);
                self.emit(&format!("bool {} = {} == {};", result_name, a_name, b_name));
            }
            GpuOp::Ne(a, b) => {
                let a_name = self.get_var_name(*a);
                let b_name = self.get_var_name(*b);
                self.emit(&format!("bool {} = {} != {};", result_name, a_name, b_name));
            }
            GpuOp::Lt(a, b) => {
                let a_name = self.get_var_name(*a);
                let b_name = self.get_var_name(*b);
                self.emit(&format!("bool {} = {} < {};", result_name, a_name, b_name));
            }
            GpuOp::Le(a, b) => {
                let a_name = self.get_var_name(*a);
                let b_name = self.get_var_name(*b);
                self.emit(&format!("bool {} = {} <= {};", result_name, a_name, b_name));
            }
            GpuOp::Gt(a, b) => {
                let a_name = self.get_var_name(*a);
                let b_name = self.get_var_name(*b);
                self.emit(&format!("bool {} = {} > {};", result_name, a_name, b_name));
            }
            GpuOp::Ge(a, b) => {
                let a_name = self.get_var_name(*a);
                let b_name = self.get_var_name(*b);
                self.emit(&format!("bool {} = {} >= {};", result_name, a_name, b_name));
            }

            // Float comparisons
            GpuOp::FEq(a, b)
            | GpuOp::FNe(a, b)
            | GpuOp::FLt(a, b)
            | GpuOp::FLe(a, b)
            | GpuOp::FGt(a, b)
            | GpuOp::FGe(a, b) => {
                let a_name = self.get_var_name(*a);
                let b_name = self.get_var_name(*b);
                let op_str = match op {
                    GpuOp::FEq(_, _) => "==",
                    GpuOp::FNe(_, _) => "!=",
                    GpuOp::FLt(_, _) => "<",
                    GpuOp::FLe(_, _) => "<=",
                    GpuOp::FGt(_, _) => ">",
                    GpuOp::FGe(_, _) => ">=",
                    _ => unreachable!(),
                };
                self.emit(&format!(
                    "bool {} = {} {} {};",
                    result_name, a_name, op_str, b_name
                ));
            }

            // Logical
            GpuOp::And(a, b) => {
                let a_name = self.get_var_name(*a);
                let b_name = self.get_var_name(*b);
                self.emit(&format!("bool {} = {} && {};", result_name, a_name, b_name));
            }
            GpuOp::Or(a, b) => {
                let a_name = self.get_var_name(*a);
                let b_name = self.get_var_name(*b);
                self.emit(&format!("bool {} = {} || {};", result_name, a_name, b_name));
            }
            GpuOp::Not(a) => {
                let a_name = self.get_var_name(*a);
                self.emit(&format!("bool {} = !{};", result_name, a_name));
            }

            // Bit operations
            GpuOp::BitAnd(a, b) => {
                let a_name = self.get_var_name(*a);
                let b_name = self.get_var_name(*b);
                self.emit(&format!("auto {} = {} & {};", result_name, a_name, b_name));
            }
            GpuOp::BitOr(a, b) => {
                let a_name = self.get_var_name(*a);
                let b_name = self.get_var_name(*b);
                self.emit(&format!("auto {} = {} | {};", result_name, a_name, b_name));
            }
            GpuOp::BitXor(a, b) => {
                let a_name = self.get_var_name(*a);
                let b_name = self.get_var_name(*b);
                self.emit(&format!("auto {} = {} ^ {};", result_name, a_name, b_name));
            }
            GpuOp::BitNot(a) => {
                let a_name = self.get_var_name(*a);
                self.emit(&format!("auto {} = ~{};", result_name, a_name));
            }
            GpuOp::Shl(a, b) => {
                let a_name = self.get_var_name(*a);
                let b_name = self.get_var_name(*b);
                self.emit(&format!("auto {} = {} << {};", result_name, a_name, b_name));
            }
            GpuOp::Shr(a, b) | GpuOp::LShr(a, b) => {
                let a_name = self.get_var_name(*a);
                let b_name = self.get_var_name(*b);
                self.emit(&format!("auto {} = {} >> {};", result_name, a_name, b_name));
            }
            GpuOp::PopCount(a) => {
                let a_name = self.get_var_name(*a);
                self.emit(&format!("uint {} = popcount({});", result_name, a_name));
            }
            GpuOp::Clz(a) => {
                let a_name = self.get_var_name(*a);
                self.emit(&format!("uint {} = clz({});", result_name, a_name));
            }
            GpuOp::Ctz(a) => {
                let a_name = self.get_var_name(*a);
                self.emit(&format!("uint {} = ctz({});", result_name, a_name));
            }

            // Conversions
            GpuOp::Trunc(a, ty) | GpuOp::ZExt(a, ty) | GpuOp::SExt(a, ty) => {
                let a_name = self.get_var_name(*a);
                let ty_str = self.type_to_msl(ty);
                self.emit(&format!(
                    "{} {} = static_cast<{}>({});",
                    ty_str, result_name, ty_str, a_name
                ));
            }
            GpuOp::FpTrunc(a, ty) | GpuOp::FpExt(a, ty) => {
                let a_name = self.get_var_name(*a);
                let ty_str = self.type_to_msl(ty);
                self.emit(&format!(
                    "{} {} = ({})({});",
                    ty_str, result_name, ty_str, a_name
                ));
            }
            GpuOp::FpToSi(a, ty) | GpuOp::FpToUi(a, ty) => {
                let a_name = self.get_var_name(*a);
                let ty_str = self.type_to_msl(ty);
                self.emit(&format!(
                    "{} {} = static_cast<{}>({});",
                    ty_str, result_name, ty_str, a_name
                ));
            }
            GpuOp::SiToFp(a, ty) | GpuOp::UiToFp(a, ty) => {
                let a_name = self.get_var_name(*a);
                let ty_str = self.type_to_msl(ty);
                self.emit(&format!(
                    "{} {} = static_cast<{}>({});",
                    ty_str, result_name, ty_str, a_name
                ));
            }
            GpuOp::Bitcast(a, ty) => {
                let a_name = self.get_var_name(*a);
                let ty_str = self.type_to_msl(ty);
                self.emit(&format!(
                    "{} {} = as_type<{}>({});",
                    ty_str, result_name, ty_str, a_name
                ));
            }

            // Memory
            GpuOp::Load(ptr, _space) => {
                let ptr_name = self.get_var_name(*ptr);
                self.emit(&format!("auto {} = *{};", result_name, ptr_name));
            }
            GpuOp::Store(ptr, val, _space) => {
                let ptr_name = self.get_var_name(*ptr);
                let val_name = self.get_var_name(*val);
                self.emit(&format!("*{} = {};", ptr_name, val_name));
            }

            // Atomics
            GpuOp::AtomicAdd(ptr, val) => {
                let ptr_name = self.get_var_name(*ptr);
                let val_name = self.get_var_name(*val);
                self.emit(&format!(
                    "auto {} = atomic_fetch_add_explicit((device atomic_int*){}, {}, memory_order_relaxed);",
                    result_name, ptr_name, val_name
                ));
            }
            GpuOp::AtomicSub(ptr, val) => {
                let ptr_name = self.get_var_name(*ptr);
                let val_name = self.get_var_name(*val);
                self.emit(&format!(
                    "auto {} = atomic_fetch_sub_explicit((device atomic_int*){}, {}, memory_order_relaxed);",
                    result_name, ptr_name, val_name
                ));
            }
            GpuOp::AtomicMin(ptr, val) => {
                let ptr_name = self.get_var_name(*ptr);
                let val_name = self.get_var_name(*val);
                self.emit(&format!(
                    "auto {} = atomic_fetch_min_explicit((device atomic_int*){}, {}, memory_order_relaxed);",
                    result_name, ptr_name, val_name
                ));
            }
            GpuOp::AtomicMax(ptr, val) => {
                let ptr_name = self.get_var_name(*ptr);
                let val_name = self.get_var_name(*val);
                self.emit(&format!(
                    "auto {} = atomic_fetch_max_explicit((device atomic_int*){}, {}, memory_order_relaxed);",
                    result_name, ptr_name, val_name
                ));
            }
            GpuOp::AtomicExch(ptr, val) => {
                let ptr_name = self.get_var_name(*ptr);
                let val_name = self.get_var_name(*val);
                self.emit(&format!(
                    "auto {} = atomic_exchange_explicit((device atomic_int*){}, {}, memory_order_relaxed);",
                    result_name, ptr_name, val_name
                ));
            }
            GpuOp::AtomicCas(ptr, cmp, val) => {
                let ptr_name = self.get_var_name(*ptr);
                let cmp_name = self.get_var_name(*cmp);
                let val_name = self.get_var_name(*val);
                self.emit(&format!("auto {}_expected = {};", result_name, cmp_name));
                self.emit(&format!(
                    "atomic_compare_exchange_weak_explicit((device atomic_int*){}, &{}_expected, {}, memory_order_relaxed, memory_order_relaxed);",
                    ptr_name, result_name, val_name
                ));
                self.emit(&format!("auto {} = {}_expected;", result_name, result_name));
            }

            // Address computation
            GpuOp::GetElementPtr(base, indices) => {
                let base_name = self.get_var_name(*base);
                let idx_strs: Vec<String> = indices.iter().map(|i| self.get_var_name(*i)).collect();
                if idx_strs.len() == 1 {
                    self.emit(&format!(
                        "auto {} = {} + {};",
                        result_name, base_name, idx_strs[0]
                    ));
                } else {
                    self.emit(&format!(
                        "auto {} = &{}[{}];",
                        result_name,
                        base_name,
                        idx_strs.join("][")
                    ));
                }
            }

            // GPU intrinsics
            GpuOp::ThreadIdX => self.emit(&format!("uint {} = threadIdx_x;", result_name)),
            GpuOp::ThreadIdY => self.emit(&format!("uint {} = threadIdx_y;", result_name)),
            GpuOp::ThreadIdZ => self.emit(&format!("uint {} = threadIdx_z;", result_name)),
            GpuOp::BlockIdX => self.emit(&format!("uint {} = blockIdx_x;", result_name)),
            GpuOp::BlockIdY => self.emit(&format!("uint {} = blockIdx_y;", result_name)),
            GpuOp::BlockIdZ => self.emit(&format!("uint {} = blockIdx_z;", result_name)),
            GpuOp::BlockDimX => self.emit(&format!("uint {} = blockDim_x;", result_name)),
            GpuOp::BlockDimY => self.emit(&format!("uint {} = blockDim_y;", result_name)),
            GpuOp::BlockDimZ => self.emit(&format!("uint {} = blockDim_z;", result_name)),
            GpuOp::GridDimX => self.emit(&format!(
                "uint {} = 0; // gridDim not directly available",
                result_name
            )),
            GpuOp::GridDimY => self.emit(&format!(
                "uint {} = 0; // gridDim not directly available",
                result_name
            )),
            GpuOp::GridDimZ => self.emit(&format!(
                "uint {} = 0; // gridDim not directly available",
                result_name
            )),
            GpuOp::WarpId => self.emit(&format!("uint {} = simd_group_id;", result_name)),
            GpuOp::LaneId => self.emit(&format!("uint {} = simd_lane_id;", result_name)),
            GpuOp::WarpSize => self.emit(&format!("uint {} = 32;", result_name)),

            // Synchronization
            GpuOp::SyncThreads => {
                self.emit("threadgroup_barrier(mem_flags::mem_threadgroup);");
            }
            GpuOp::SyncWarp(_mask) => {
                self.emit("simdgroup_barrier(mem_flags::mem_none);");
            }
            GpuOp::MemoryFence(space) => {
                let flag = match space {
                    MemorySpace::Shared => "mem_flags::mem_threadgroup",
                    MemorySpace::Global => "mem_flags::mem_device",
                    _ => "mem_flags::mem_none",
                };
                self.emit(&format!("threadgroup_barrier({});", flag));
            }

            // Simdgroup (warp) operations
            GpuOp::WarpShuffle(val, lane) => {
                let val_name = self.get_var_name(*val);
                let lane_name = self.get_var_name(*lane);
                self.emit(&format!(
                    "auto {} = simd_shuffle({}, {});",
                    result_name, val_name, lane_name
                ));
            }
            GpuOp::WarpShuffleUp(val, delta) => {
                let val_name = self.get_var_name(*val);
                let delta_name = self.get_var_name(*delta);
                self.emit(&format!(
                    "auto {} = simd_shuffle_up({}, {});",
                    result_name, val_name, delta_name
                ));
            }
            GpuOp::WarpShuffleDown(val, delta) => {
                let val_name = self.get_var_name(*val);
                let delta_name = self.get_var_name(*delta);
                self.emit(&format!(
                    "auto {} = simd_shuffle_down({}, {});",
                    result_name, val_name, delta_name
                ));
            }
            GpuOp::WarpShuffleXor(val, mask) => {
                let val_name = self.get_var_name(*val);
                let mask_name = self.get_var_name(*mask);
                self.emit(&format!(
                    "auto {} = simd_shuffle_xor({}, {});",
                    result_name, val_name, mask_name
                ));
            }
            GpuOp::WarpVote(vote_op, val) => {
                let val_name = self.get_var_name(*val);
                let func = match vote_op {
                    WarpVoteOp::All => "simd_all",
                    WarpVoteOp::Any => "simd_any",
                    WarpVoteOp::Ballot => "simd_ballot",
                    WarpVoteOp::Eq => "simd_all",
                };
                self.emit(&format!("auto {} = {}({});", result_name, func, val_name));
            }
            GpuOp::WarpReduce(reduce_op, val) => {
                let val_name = self.get_var_name(*val);
                let func = match reduce_op {
                    WarpReduceOp::Add => "simd_sum",
                    WarpReduceOp::Min => "simd_min",
                    WarpReduceOp::Max => "simd_max",
                    WarpReduceOp::And => "simd_and",
                    WarpReduceOp::Or => "simd_or",
                    WarpReduceOp::Xor => "simd_xor",
                };
                self.emit(&format!("auto {} = {}({});", result_name, func, val_name));
            }

            // Control flow
            GpuOp::Select(cond, t, f) => {
                let cond_name = self.get_var_name(*cond);
                let t_name = self.get_var_name(*t);
                let f_name = self.get_var_name(*f);
                self.emit(&format!(
                    "auto {} = {} ? {} : {};",
                    result_name, cond_name, t_name, f_name
                ));
            }

            // Function call
            GpuOp::Call(func_name, args) => {
                let args_str: Vec<String> = args.iter().map(|a| self.get_var_name(*a)).collect();
                self.emit(&format!(
                    "auto {} = {}({});",
                    result_name,
                    func_name,
                    args_str.join(", ")
                ));
            }

            // Parameter
            GpuOp::Param(idx) => {
                self.emit(&format!("// param {} -> {}", idx, result_name));
            }

            // Shared memory address
            GpuOp::SharedAddr(name) => {
                self.emit(&format!("auto {} = &{}[0];", result_name, name));
            }

            // Phi nodes (handled by SSA deconstruction)
            GpuOp::Phi(_) => {
                self.emit(&format!("// phi -> {} (handled separately)", result_name));
            }

            // Texture/Surface (not yet implemented)
            GpuOp::TexFetch(_, _)
            | GpuOp::TexFetch2D(_, _, _)
            | GpuOp::SurfRead(_, _)
            | GpuOp::SurfWrite(_, _, _) => {
                self.emit(&format!(
                    "// Texture op -> {} (not yet implemented)",
                    result_name
                ));
            }

            // Remaining ops
            _ => {
                self.emit(&format!("// Unhandled op -> {}", result_name));
            }
        }
    }

    fn emit_terminator(&mut self, term: &GpuTerminator) {
        match term {
            GpuTerminator::Br(target) => {
                self.emit(&format!("goto BB{};", target.0));
            }
            GpuTerminator::CondBr(cond, t, f) => {
                let cond_name = self.get_var_name(*cond);
                self.emit(&format!(
                    "if ({}) goto BB{}; else goto BB{};",
                    cond_name, t.0, f.0
                ));
            }
            GpuTerminator::Return(val) => {
                let val_name = self.get_var_name(*val);
                self.emit(&format!("return {};", val_name));
            }
            GpuTerminator::ReturnVoid => {
                self.emit("return;");
            }
            GpuTerminator::Unreachable => {
                self.emit("// unreachable");
            }
        }
    }

    fn get_or_create_var_name(&mut self, id: ValueId) -> String {
        if let Some(name) = self.value_names.get(&id) {
            name.clone()
        } else {
            let name = format!("v{}", id.0);
            self.value_names.insert(id, name.clone());
            name
        }
    }

    fn get_var_name(&self, id: ValueId) -> String {
        self.value_names
            .get(&id)
            .cloned()
            .unwrap_or_else(|| format!("v{}", id.0))
    }

    fn type_to_msl(&self, ty: &GpuType) -> &'static str {
        match ty {
            GpuType::Void => "void",
            GpuType::Bool => "bool",
            GpuType::I8 => "char",
            GpuType::I16 => "short",
            GpuType::I32 => "int",
            GpuType::I64 => "long",
            GpuType::U8 => "uchar",
            GpuType::U16 => "ushort",
            GpuType::U32 => "uint",
            GpuType::U64 => "ulong",
            GpuType::F16 => "half",
            GpuType::F32 => "float",
            GpuType::F64 => "float", // Metal doesn't have native double on all devices
            GpuType::Vec2(_) => "float2",
            GpuType::Vec3(_) => "float3",
            GpuType::Vec4(_) => "float4",
            GpuType::Ptr(_, _) => "device void*",
            GpuType::Array(_, _) => "void*",
            GpuType::Struct(name, _) => {
                // Return leaked str to get 'static lifetime
                // This is a workaround for the signature
                Box::leak(name.clone().into_boxed_str())
            }
        }
    }

    fn memory_space_to_msl(&self, space: MemorySpace) -> &'static str {
        match space {
            MemorySpace::Global => "device",
            MemorySpace::Shared => "threadgroup",
            MemorySpace::Local => "thread",
            MemorySpace::Constant => "constant",
            MemorySpace::Texture => "texture2d<float>",
            MemorySpace::Generic => "device",
        }
    }

    fn params_to_msl(&self, params: &[GpuParam]) -> String {
        params
            .iter()
            .map(|p| {
                let ty = self.type_to_msl(&p.ty);
                let space = self.memory_space_to_msl(p.space);
                format!("{} {} {}", space, ty, p.name)
            })
            .collect::<Vec<_>>()
            .join(", ")
    }

    fn const_value_to_msl(&self, val: &GpuConstValue) -> String {
        match val {
            GpuConstValue::Int(i) => i.to_string(),
            GpuConstValue::Float(f) => format!("{}f", f),
            GpuConstValue::Bool(b) => b.to_string(),
            GpuConstValue::Array(vals) => {
                let items: Vec<String> = vals.iter().map(|v| self.const_value_to_msl(v)).collect();
                format!("{{{}}}", items.join(", "))
            }
            GpuConstValue::Struct(vals) => {
                let items: Vec<String> = vals.iter().map(|v| self.const_value_to_msl(v)).collect();
                format!("{{{}}}", items.join(", "))
            }
        }
    }
}

/// Compile HLIR to MSL
pub fn compile_to_msl(hlir: &crate::hlir::HlirModule, gpu_family: MetalGpuFamily) -> String {
    use super::hlir_to_gpu::{LoweringConfig, lower_with_config};

    let config = LoweringConfig {
        target: GpuTarget::Metal { gpu_family },
        epistemic_enabled: true,
        ..Default::default()
    };

    let gpu_module = lower_with_config(hlir, &config);

    let mut codegen = MetalCodegen::new(MetalCodegenConfig {
        gpu_family,
        epistemic_enabled: true,
        ..Default::default()
    });

    codegen.generate(&gpu_module)
}

/// Compile HLIR to MSL with epistemic tracking
pub fn compile_to_msl_epistemic(
    hlir: &crate::hlir::HlirModule,
    gpu_family: MetalGpuFamily,
    epistemic: bool,
) -> String {
    use super::hlir_to_gpu::{LoweringConfig, lower_with_config};

    let config = LoweringConfig {
        target: GpuTarget::Metal { gpu_family },
        epistemic_enabled: epistemic,
        ..Default::default()
    };

    let gpu_module = lower_with_config(hlir, &config);

    let mut codegen = MetalCodegen::new(MetalCodegenConfig {
        gpu_family,
        epistemic_enabled: epistemic,
        ..Default::default()
    });

    codegen.generate(&gpu_module)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_metal_gpu_family() {
        assert_eq!(MetalGpuFamily::Apple8.simd_width(), 32);
        assert_eq!(MetalGpuFamily::Apple9.msl_version(), "3.1");
        assert!(MetalGpuFamily::Apple7.supports_simdgroup_matrix());
    }

    #[test]
    fn test_metal_codegen_empty() {
        let module = GpuModule::new(
            "test",
            GpuTarget::Metal {
                gpu_family: MetalGpuFamily::Apple8,
            },
        );

        let mut codegen = MetalCodegen::new(MetalCodegenConfig::default());
        let msl = codegen.generate(&module);

        assert!(msl.contains("#include <metal_stdlib>"));
        assert!(msl.contains("EpistemicFloat"));
        assert!(msl.contains("epistemic_add"));
    }

    #[test]
    fn test_epistemic_types_generated() {
        let module = GpuModule::new(
            "test",
            GpuTarget::Metal {
                gpu_family: MetalGpuFamily::Apple8,
            },
        );

        let mut codegen = MetalCodegen::new(MetalCodegenConfig {
            epistemic_enabled: true,
            ..Default::default()
        });
        let msl = codegen.generate(&module);

        assert!(msl.contains("struct EpistemicFloat"));
        assert!(msl.contains("float epsilon"));
        assert!(msl.contains("uint64_t provenance"));
        assert!(msl.contains("epistemic_mul"));
        assert!(msl.contains("epistemic_div"));
        assert!(msl.contains("simdgroup_epsilon_max"));
    }
}
